res = 0 #VARIABLE AUXILIAR, PUES EL EL XOR SIEMPRE NOS RETURNARA 'N' CUANDO LO COMPARAMOS CON UN 0
nums = [4,1,2,1,2] #INPUT

for n in nums: #SE CHECA CADA NUMERO
    res = n ^ res #EMPEZAMOS A HACER EL XOR POR CADA NUMERO

print(res)